events {}

http {
  server {
    listen 80;

    # front
    location / {
      proxy_pass http://todo-frontend:80;
    }

    # back
    location /api/ {
      proxy_pass http://todo-backend:3000/;
    }
  }
}
